### ISSUE TITLE
Please consider adding a switch component to start charging

### ISSUE THREAD

**Issue by jumpkick** [zabuldon/teslajsonpy#1]
A switch component for charging would be helpful, so that HA could manage more advanced charging scenarios/rules than the Tesla is able to handle on its own through schedule charging.

Here are some possible usage scenarios of having a charging switch within HA:
* automatically start charging the car if it is plugged in on a weekend (where I live we have Time-of-Use cost of electricity, 7p-7a on weekdays and all sat/sun are lowest rate).
* automatically stop charging the car after 7a on weekdays (save $ from ToU)
* automatically charge the car if the State of Charge is below a certain level (i.e. <15% battery) 
* automatically stop charging if the house's energy usage rises above a certain Kw level (my house has 100A service (~23kW), my charger is 48A (11.5kW), if the oven and clothes dryer and A/C are running at the same time, starting to charge could trip the main breaker)

**Comment by zabuldon** [comment]
Added ChargerSwitch.
