### ISSUE TITLE
Support opening primary homelink device with trigger_homelink

### ISSUE THREAD

**Issue by heikkih** [zabuldon/teslajsonpy#110]
Hi.

I'd really like to see the homelink-integration in this api like https://tesla-api.timdorr.com/vehicle/commands/homelink

I see that the tests have included a homelink_device_count = 0.

Are there any plans to support this?

Best regards

**Comment by alandtse** [comment]
Just needs someone to implement it or request it. I assume your'e asking because you want this in HA right?

**Comment by alandtse** [comment]
One issue we may have to figure out is the API is saying you need to provide lat and lon. I don't think we have access to this data in HA.

**Comment by heikkih** [comment]
Would be nice to have this in HA, yes.

Also agree that latitude and longitude must be the cars coordinate, as those are then linked to the coordinates of the homelink-device internally in the car. I have tested and verified this using the homelink-button in the Tesla-app.

**Comment by alandtse** [comment]
Just to be clear, the official app actually provides the mobile devices coords to the API so you can't issue the homelink command if you're not near your vehicle. This probably to prevent someone from accidentally opening their garage door when they're not at home. We'll be removing that protection from the call.

**Comment by appleguru** [comment]
> Just to be clear, the official app actually provides the mobile devices coords to the API so you can't issue the homelink command if you're not near your vehicle. This probably to prevent someone from accidentally opening their garage door when they're not at home. We'll be removing that protection from the call.

This is exactly the behavior I'm looking for. +1 to this request.

**Comment by EvTheFuture** [comment]
This is on my to-do list if not anyone else is already working on this?

**Comment by alandtse** [comment]
This is available using `controller.api` with [`TRIGGER_HOMELINK`](https://github.com/zabuldon/teslajsonpy/blob/dev/teslajsonpy/endpoints.json#L147-L151).
