### ISSUE TITLE
Adding powerwall 2 support

### ISSUE THREAD

**Issue by johanndt** [zabuldon/teslajsonpy#13]
By querying `https://owner-api.teslamotors.com/api/1/products` I can get a list of all power walls linked to an account along with some basic info such as charge rate and level.

I'd like to get this into HA, and since it uses this library it makes sense for me to add it here - the login mechanism etc are exactly the same. But before I add the code I just wanted to check if this is still active and if such a PR would be accepted?

**Comment by zabuldon** [comment]
@johanndt, yes it is still active project. I just was in a long holiday.

**Comment by johanndt** [comment]
Thanks @OverloadUT and @zabuldon. I can hopefully get something together over the next couple of weeks. As always things are pretty busy for everyone. :-)

**Comment by zabuldon** [comment]
@johanndt is this still actual?

**Comment by alandtse** [comment]
@johanndt Let us know if you're still interested in this, otherwise we'll probably close this issue until you're ready. I am assisting @zabuldon, so the update rate should increase if you're interested.

Unfortunately I haven't ordered a powerwall so can't test this.

**Comment by johanndt** [comment]
Yes please close. I'm sorry but I life and work got in the way. :-(

**Comment by alandtse** [comment]
No biggie. Please reopen if you have more time to address this and we'll be happy to merge it in.
