### ISSUE TITLE
Add read the docs support

### ISSUE THREAD

**Issue by alandtse** [zabuldon/teslajsonpy#151]
Hi @zabuldon, I just added sphinx support to the repo. Can you enable it on https://readthedocs.org/ please?

Edit: forgot my manners.

**Comment by zabuldon** [comment]
Not sure if I can do this. As there is a project with the same name https://readthedocs.org/projects/teslajsonpy/ created by you  https://readthedocs.org/profiles/alandtse/

**Comment by alandtse** [comment]
Sorry, it's gone now. I created it and didn't have the rights but forgot to remove it.

**Comment by alandtse** [comment]
@zabuldon This is ready whenever you have the time.

**Comment by zabuldon** [comment]
@alandtse config was added but documentation build fails with error:

[https://readthedocs.org/api/v2/build/13138360.txt](url)
