### ISSUE TITLE
Cannot authorize with accounts registered under auth.tesla.cn

### ISSUE THREAD

**Issue by woodchen** [zabuldon/teslajsonpy#159]
According to https://tesla-api.timdorr.com/api-basics/authentication

When the optional login_hint parameter is supplied with the GET request and the email is registered with a Tesla SSO service in another region this will respond with a 303 HTTP response code (See Other), which will redirect you to the Tesla SSO service in that region (e.g. auth.tesla.cn). Should this redirect happen you should continue using the region specific Tesla SSO host name in all subsequent steps. Easy way to test this is to use auth.tesla.cn with login_hint using an email registered under auth.tesla.com.

**Comment by alandtse** [comment]
Thanks.

**Comment by alandtse** [comment]
I need to test whether the Tesla login at auth.tesla.com will automatically send you to auth.tesla.cn. It works the opposite way in my testing. 

Please report findings here: https://github.com/home-assistant/core/pull/46558
