### ISSUE TITLE
Update-frequency while connected to a charger

### ISSUE THREAD

**Issue by Olen** [zabuldon/teslajsonpy#166]
Today, the polling interval will be set back to default (11 minutes) when the car moves from "Charging" to e.g "Complete", even if the car is still connected to the charger.
I don't know if this is intentional, but personally, I would prefer to keep on polling every minute even if the charging is done as long as it is still _connected_ to  charger.

https://github.com/zabuldon/teslajsonpy/blob/5889b896dc20c11b4b2342cdd4af7963f6ad24e8/teslajsonpy/controller.py#L628

I don't know the best way to check if the car is still connected to the charger, as it has been some years since I played with the api, and remember from "back then" that some values could be a bit unreliable, and was lingering even after they should have been reset.
Some ideas:
- add an "or charging_state == 'Complete' (and maybe also 'Starting to charge" or whatever it is called) 
- add a check for 'charge_port_latch' == 'Enaged' 
- add a check for 'charger_pilot_current' > 0
- add a check for 'conn_charge_cable' is not None

If the drop in poll rate is intended, I would like to add something like a "always_poll_on_charger_connected" flag, so you can keep the default of not polling, but the user kan increase polling frequency if he wants.

**Comment by alandtse** [comment]
It is intentional to allow the car to sleep since it is no longer charging. Otherwise it will unnecessarily drain the battery which has real world costs.

**Comment by Olen** [comment]
Thanks.

I wanted to check if there was any chance of it being implemented before doing the job.
But I'll see if I can add a PR.  I'll probably implement it as a flag, so you can set something like 
"wake_up_policy:" 
- "always"  (just keep the car awake, no matter what)
- "connected" (keep it awake while connected to a charger, even if charging is completed)
- "charging" (current implementation, and default)

Does this sound like a reasonable approach?

**Comment by alandtse** [comment]
Yes. But I don't think always is a good idea. You can select multiple flags and just populate the default and your setting.

Please note the latest dev branch is built to be used with the current [PR](https://github.com/home-assistant/core/pull/46558) to HA which is in testing.

**Comment by Olen** [comment]
I have been running "always" forever, due to another 3. party app that has not implemented any sleep mode at all, and it has never caused any problem.  Whether it is a good idea or not, and how much it will cost you in terms of money and lost range while parked, is of course up to each to decide.

I'll add the PR here first, and it should be fairly easy to add it to the tesla integration in HA after that.

**Comment by Olen** [comment]
Closing this as it has been fixed in the latest merge.
