### ISSUE TITLE
KeyError: 'climate_state'

### ISSUE THREAD

**Issue by alandtse** [zabuldon/teslajsonpy#186]
@Trupal00p 

I'm getting this error in a live system. Can you please check and provide a fix? Please note there will be vehicles that may not have seat heaters.

```
  File "/workspaces/home-assistant/homeassistant/components/tesla/config_flow.py", line 229, in validate_input
    config = await controller.connect(
  File "/workspaces/home-assistant/config/teslajsonpy/controller.py", line 316, in connect
    self._add_components(car)
  File "/workspaces/home-assistant/config/teslajsonpy/controller.py", line 549, in _add_components
    self.__components.append(HeatedSeatSwitch(car, self, 'left'))
  File "/workspaces/home-assistant/config/teslajsonpy/homeassistant/heated_seats.py", line 47, in __init__
    self.__seat_heat_level = data['climate_state'][f'seat_heater_{seat_name}']
KeyError: 'climate_state'
```

I'll spawn a new issue with this comment so please respond there.

_Originally posted by @alandtse in https://github.com/zabuldon/teslajsonpy/issues/180#issuecomment-812803500_

**Comment by alandtse** [comment]
I will put a temporary fix that won't load the seat sensors if a keyerror is found. That may be the solution, but I'd appreciate you taking a look and maybe considering another fix with a test for this case.

**Comment by alandtse** [comment]
It looks like you're relying on the sensors to be enabled. However, the data won't have been pulled yet during init. You should move that into the update function.

**Comment by Trupal00p** [comment]
Just opened a PR to fix this.  Thanks for clarifying what was causing the issue, misunderstood the lifecycle of the tesla data when I originally added.
