### ISSUE TITLE
Parking Sensor might be better called Parking Brake or Drive/Gear/Shift State Sensor

### ISSUE THREAD

**Issue by jumpkick** [zabuldon/teslajsonpy#2]
This isn't terribly important... the usage of "Parking Sensor" to indicate the car's shift state could confuse some folks into thinking the sensor has something to do with the Parking Sensors (sonar/ultrasonic sensors) that dot the perimeter of Teslas manufactured after 2014.

Feel free to mark as won't fix 😄

**Comment by zabuldon** [comment]
Fixed
