### ISSUE TITLE
`get_location()` not updating if car is parked facing north

### ISSUE THREAD

**Issue by itssimon** [zabuldon/teslajsonpy#276]
I'm using the `tesla_custom` custom component in Home Assistant and have been wondering why the location of our car is often reported as away or unknown by the `device_tracker` entity in HA if the car is parked in our garage.

I found the culprit in this line of code:
https://github.com/zabuldon/teslajsonpy/blob/bd67913b1088ba1ac112e3e67a434e4f2da1ef7d/teslajsonpy/homeassistant/gps.py#L51

It just so happens that our garage is facing almost perfectly north, which means that often the Tesla API will return a `heading` value of `0`, which of course evaluates to `false` and makes the `get_location()` not update the value or return an empty dict.

**Comment by alandtse** [comment]
Wow, nice catch and a good sign of proper boolean checking.
