### ISSUE TITLE
ERROR: Cannot install teslajsonpy because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by purcell-lab** [zabuldon/teslajsonpy#285]
I am seeing an issue surface in the new beta HA release core-2022.3.0b0, which is unable to load this package.

Looks like it is a new requirement of pip, which needs to be fixed in teslajsonpy to ensure valid dependencies.

References:

https://github.com/alandtse/tesla/issues/151
https://github.com/home-assistant/home-assistant.io/issues/21766
https://github.com/pypa/pip/issues/10825

```
Unable to install package teslajsonpy==1.5.0: 
warning: missing-index-doctype 
× The package index page being used does not have a proper HTML doctype declaration. 
╰─> Problematic URL: https://wheels.home-assistant.io/alpine-3.14/aarch64/ 
note: This is an issue with the page at the URL mentioned above. hint: You might need to reach out to the owner of that package index, to get this fixed. See https://github.com/pypa/pip/issues/10825 for context. 

ERROR: Cannot install teslajsonpy because these package versions have conflicting dependencies. 
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by purcell-lab** [comment]
We need to get something like this fix, for teslajsonpy:

https://github.com/leikoilja/glocaltokens/pull/219

Addressing the teslajsonpy dependencies:

https://github.com/zabuldon/teslajsonpy/blob/76ddb1cbe4e1d467abade5f32610df3dfde9d1ab/pyproject.toml#L28-L35

**Comment by alandtse** [comment]
Should be fixed by https://github.com/alandtse/auth_capture_proxy/pull/20
