### ISSUE TITLE
Swap to Apache-2.0

### ISSUE THREAD

**Issue by alandtse** [zabuldon/teslajsonpy#29]
Given HA is [Apache-2.0](https://github.com/home-assistant/home-assistant/blob/dev/LICENSE.md), I think we should swap this over to Apache-2.0 instead of WTFPL to be consistent.

@zabuldon Any objections since you chose the initial license? I can handle the migration, flagged you so you'd see it.

**Comment by alandtse** [comment]
Flagging other contributors for objectinos: @ultratoto14 @johanjongsma

**Comment by zabuldon** [comment]
Why do we need to change the license? Wtfpl is compatible almost any permissive license.

**Comment by alandtse** [comment]
Couple of issues beyond a compatibility issue:

- It doesn't disclaim warranties. That means all of us may potentially be sued if it bricks someone's Tesla. Some of us are in the US where people are sue-happy. There's a couple links you can review: [0](https://www.gnu.org/licenses/license-list.html#WTFPL),[1](https://news.ycombinator.com/item?id=8104407)
- It's ambiguous on whether we're actually licensing the code for people to use. Specifically, it doesn't mention the code at all and one interpretation is it's a public domain declaration which may not be [recognized in Europe](https://en.wikipedia.org/wiki/WTFPL#Discussion).
>   0. You just DO WHAT THE FUCK YOU WANT TO.

**Comment by zabuldon** [comment]
Ok. Feel free to change

**Comment by zabuldon** [comment]
@alandtse I think it can be closed. Or not?
