### ISSUE TITLE
Consider moving the `vehicle_data` attribute into a disabled by default entity (`entity_registry_enabled_default=False`)

### ISSUE THREAD

**Issue by bdraco** [zabuldon/teslajsonpy#298]
This sensor attribute which was added in https://github.com/zabuldon/teslajsonpy/pull/279 takes quite a bit of database space because it can't be de-duplicated since at least one of the attributes always changes.  Additionally every client (include mobiles) that connect has to serialize/download/deserialize the full state before the UI loads, and then process every update.

https://github.com/zabuldon/teslajsonpy/blob/dev/teslajsonpy/homeassistant/binary_sensor.py#L220

https://developers.home-assistant.io/docs/core/entity?_highlight=entit#generic-properties
Entities that generate a significant amount of state changes can quickly increase the size of the database when the extra_state_attributes also change frequently. Minimize the number of extra_state_attributes for these entities by removing non-critical attributes or creating additional sensor entities.

https://developers.home-assistant.io/docs/core/entity?_highlight=gener#advanced-properties
`entity_registry_enabled_default=False`

cc @ehendrix23 

As a workaround, I disabled the online binary sensor, but that is one of the ones I did find useful.

**Comment by ehendrix23** [comment]
Hey Nick,

But this is only saved when state changes correct? When I was checking into it there did not seem to be anything saved unless the state itself changed.

Will see to make different sensor(s) (maybe 1 for each area) with disabled by default allowing some more selection then what someone wants enabled.
If indeed only saved on state change, which I assume it is, maybe then further have more of a fixed state to reduce saving and thus database growth?
Thoughts?

**Comment by bdraco** [comment]
Hi Erik,

Thanks for following up 😄 

> But this is only saved when state changes correct? When I was checking into it there did not seem to be anything saved unless the state itself changed.

If any of the attributes change (https://github.com/home-assistant/core/blob/dev/homeassistant/core.py#L1353), the `state_changed` event will be fired and the entire set of attributes+state will be written to the database along with the `last_updated` timestamp changes.  The `last_changed` timestamp only changes when the actual state changes (https://github.com/home-assistant/core/blob/dev/homeassistant/core.py#L1351).  Both end up firing the `state_changed` event and writing to the db

In 2022.4 and later (not yet released), when the same set of state attributes (exact same) already exists in the database, newly recorded state changes now only store a reference to the state attributes instead of saving the whole set of state attributes.  

> Will see to make different sensor(s) (maybe 1 for each area) with disabled by default allowing some more selection then what someone wants enabled.

That sounds like a good solution. 👍 


For clarity on how the new attributes storage works.  Something like this will only get stored once:
```
> select * from state_attributes limit 5; 
1|119744166|{"state_class":"total_increasing","unit_of_measurement":"kWh","device_class":"energy","icon":"mdi:circle-slice-3","friendly_name":"West Garden Lights Total Daily Energy"}
2|3355382160|{"state_class":"measurement","unit_of_measurement":"%","attribution":"Data provided by Synology","icon":"mdi:chip","friendly_name":"mauinasa CPU Utilization (Total)"}
3|4077671145|{"unit_of_measurement":"load","attribution":"Data provided by Synology","icon":"mdi:chip","friendly_name":"mauinasa CPU Load Average (5 min)"}
```

Something like this gets stored every time.
```
37138|832244638|{"next_dawn":"2022-03-25T16:03:37.331293+00:00","next_dusk":"2022-03-26T05:01:48.295139+00:00","next_midnight":"2022-03-25T10:32:32+00:00","next_noon":"2022-03-25T22:32:49+00:00","next_rising":"2022-03-25T16:26:11.933165+00:00","next_setting":"2022-03-26T04:39:12.023564+00:00","elevation":-52.9,"azimuth":304.29,"rising":false,"friendly_name":"Sun"}
```

**Comment by bdraco** [comment]
Thanks 🚀

**Comment by ehendrix23** [comment]
Hey Nick,

No problem. :-)

One quick question, with this change that additional data is in separate sensors but based on what you state when enabled will still result in a lot of data being stored as attributes would change.
But if excluding them from the recorder then that would prevent this correct? Checking as if it does then I'll be updating the README for the component suggesting them to be excluded.

Thx.

**Comment by bdraco** [comment]
> But if excluding them from the recorder then that would prevent this correct? Checking as if it does then I'll be updating the README for the component suggesting them to be excluded.

Yes thats correct.  It won't exclude them from updates and initial state being sent down the websocket stream but if they are disabled by default that seems like it won't be an issue for most.
