### ISSUE TITLE
HA Tesla component wishlist...

### ISSUE THREAD

**Issue by jumpkick** [zabuldon/teslajsonpy#3]
- Change Tesla Battery Sensor display from Rainbow bars to line graph type (this may be as easy as assigning a percentage unit_of_measurement)
  - Merge PR https://github.com/zabuldon/home-assistant/pull/1
- Remove trailing period (.) from all Tesla components to match the rest of HA
- "Model S", "Model X", "Model 3" are names so "M" in model should be capital if possible
- If there's a way to drop model/vin from single vehicle households that may be helpful in making scripts/automations more portable.  i.e. if len(vehicles) < 2:  name objects switch.tesla_charger_switch, else: switch.tesla_YOURMODEL_YOURVIN_charger_switch

**Comment by alandtse** [comment]
For the VIN, I think we should actually truncate to the last 5 digits so people aren't posting their VIN online if they share their scripts.  Of course changing the sensor names will break existing configs.
