### ISSUE TITLE
KeyError: `access_token` - Tesla updated their authentication method

### ISSUE THREAD

**Issue by ereOn** [zabuldon/teslajsonpy#313]
Hi,

The Home Assistant integration recently stopped working by complaining that the returned response does not contain an `access_token` field anymore.

Here is a screenshot of the error on my setup:

![image](https://user-images.githubusercontent.com/585131/165523134-0246f42b-99a4-4bc9-92b6-73d4c8071b9c.png)

Some other people have been experiencing the same issue around the same time I started getting it: https://community.home-assistant.io/t/tesla-custom-integration-error/415134

Enabling debug logging gives out more information:

```
2022-04-27 09:03:53 DEBUG (MainThread) [teslajsonpy.connection] Exchanging bearer token with access token:                                                                              
2022-04-27 09:03:54 DEBUG (MainThread) [teslajsonpy.connection] Received bearer token {'response': 'unsupported_authentication_method_-_please_update_to_the_latest_version'} 
```

So it seems Tesla updated their authentication method. I would make a PR to try and fix this, but I wouldn't know where to start to find the proper authentication method on Tesla's side.

Would you have any pointers?

Thank you.

P.S:  Thanks a lot for all the good work you've put in with that library: it's great!

**Comment by alandtse** [comment]
This was fixed months ago. https://github.com/alandtse/tesla/issues/165 Please confirm you have teslajsonpy 2.1.0

**Comment by alandtse** [comment]
Please reopen if that wasn't the resolution.
