### ISSUE TITLE
json: cannot unmarshal string into Go struct field OperationUpdateContainer.backup_reserve_percent of type float64 

### ISSUE THREAD

**Issue by crackers8199** [zabuldon/teslajsonpy#316]
trying to run BACKUP_RESERVE on my powerwalls, and getting the following error:

```
2022-05-11 23:15:55 DEBUG (MainThread) [teslajsonpy.connection] post: https://owner-api.teslamotors.com/api/1/energy_sites/xxx/backup {'backup_reserve_percent': '20'}
2022-05-11 23:15:55 DEBUG (MainThread) [teslajsonpy.connection] 400: {"response":null,"error":"https://powergate.prd.sn.tesla.services:443/api/v2/energy_site/backup => Unable to read backup reserve payload --(Error)--> [[ json: cannot unmarshal string into Go struct field OperationUpdateContainer.backup_reserve_percent of type float64 ]]","error_description":""}
2022-05-11 23:15:55 DEBUG (MainThread) [teslajsonpy.controller] Exception: 
api(() {'name': 'BACKUP_RESERVE', 'path_vars': {'site_id': 'xxx'}, 'backup_reserve_percent': '20'})
```

i've tried sending 20, '20', "20", everything i can think of...it always ends up with the same error. it works if i try to run OPERATION_MODE and set it to 'self_consumption' or 'autonomous' so it seems to be an issue with numbers specifically...i tried poking around in the code to see if i could figure it out, but i'm getting nowhere.

i know the actual endpoint does work, because it works if i run it via TeslaPy on the same machine...

```
python3 cli.py -e xxx@xxx.com -a BACKUP_RESERVE -k backup_reserve_percent=20
```

**Comment by alandtse** [comment]
We're literally passing the the kwargs dict straight to httpx and on to tesla's servers. I don't know what calls your cli.py does, but you can compare that with a debugger.

https://github.com/zabuldon/teslajsonpy/blob/dev/teslajsonpy/controller.py#L1801-L1804

It's also quite possible that our endpoints file is also out of date. I don't have a powerwall so can't test anything for you.
https://github.com/zabuldon/teslajsonpy/blob/dev/teslajsonpy/endpoints.json

**Comment by alandtse** [comment]
Btw, the error is saying you can't pass a string, so it has to be `20` not `'20'`

**Comment by crackers8199** [comment]
as I said, I've tried every possible way I can think of (including trying to use a template to cast it). same error every time.

it doesn't seem to be an issue with the endpoint not being there, it has no problem finding it...it's an issue with the value somehow.

**Comment by crackers8199** [comment]
as for what calls cli.py does, it's stock from teslaPy. the only change I made to it was to limit it to my battery rather than also pulling my car.

**Comment by crackers8199** [comment]
something is still wrong here even after upgrading HA to 2022.6.7. 

the API calls for powerwalls work otherwise, because i can set the operation mode just fine.

no matter what i try to pass here for something involving a float, it just will not work. it gives that same error every time...i have tried every possible combination i can think of to try to get it to cast this thing into a float, and it just won't work. if i'm doing something wrong, please let me know...but this seems like it has to be an issue with teslajsonpy somehow and how it handles numeric values coming from HA.

```
service: tesla_custom.api
data:
  command: BACKUP_RESERVE
  parameters:
    path_vars:
      site_id: 'xxx'
    backup_reserve_percent: '{{ 40 | float }}'
```

```
2022-06-24 17:43:52 DEBUG (MainThread) [teslajsonpy.connection] post: https://owner-api.teslamotors.com/api/1/energy_sites/xxx/backup {'backup_reserve_percent': 40.0}
2022-06-24 17:43:52 DEBUG (MainThread) [teslajsonpy.connection] 400: {"response":null,"error":"https://powergate.prd.sn.tesla.services:443/api/v2/energy_site/backup => Unable to read backup reserve payload --(Error)--> [[ json: cannot unmarshal string into Go struct field OperationUpdateContainer.backup_reserve_percent of type float64 ]]","error_description":""}
2022-06-24 17:43:52 DEBUG (MainThread) [teslajsonpy.controller] Exception: 
api(() {'name': 'BACKUP_RESERVE', 'path_vars': {'site_id': 'xxx'}, 'backup_reserve_percent': 40.0})
```

**Comment by alandtse** [comment]
Just to reiterate, I can't debug this since I don't have a powerwall so it'll have to be you or someone else who is interested. I've already pointed out where in the code to start and that it ultimately goes down to httpx without any processing by the component. It quite possibly could be a bug in httpx or in this library, but I'm not spending any time on it.

I'll go ahead and edit my original post to point at the specific line for the httpx call and it's an exercise to the reader to confirm we're not touching any of the data args.

**Comment by crackers8199** [comment]
as i said, it isn't a powerwall specific issue. it's an issue with either the way HA is passing numbers or the way this library is handling it.

any calls made that use strings work fine. it just happens to be a powerwall call that i'm referencing here, but ANY call that uses a numeric param is going to have the same issue. i'll see if i can find one that is vehicle specific.

**Comment by crackers8199** [comment]
alright, i'm wrong. it works with numeric values on vehicle specific endpoints...but i don't understand (at all) why that would be the case. if it's just passing values directly as you say it is, there's no reason a powerwall call shouldn't work just the same as the vehicle calls do.

i'm happy to help debug this but all of my attempts have failed. as far as i can see, this should be passing a float but it's somehow still getting a string.

**Comment by crackers8199** [comment]
the debugger line right above the connection.py line you linked to is logging it and seems to show that it's a float, does it not?

```
2022-06-24 18:24:43 DEBUG (MainThread) [teslajsonpy.connection] post: https://owner-api.teslamotors.com/api/1/energy_sites/2252106687966986/backup {'backup_reserve_percent': 40.0}
```

**Comment by alandtse** [comment]
Yes. If you attach a debugger, you can try querying its type.

**Comment by crackers8199** [comment]
I have no idea how to do that.
