### ISSUE TITLE
Change Trunk, Frunk and Battery Door to be cover and not lock

### ISSUE THREAD

**Issue by chrisdrackett** [zabuldon/teslajsonpy#348]
I think these entities make more sense as the type `cover` with a class of `DEVICE_CLASS_DOOR` vs. locks as it aligns to how they work better (these controls open and close something and have a status).

**Comment by shred86** [comment]
I'll add this to the rewrite but for the frunk, are there any Tesla's that actually have a powered frunk? My 2015 Model S only has an option to "open" that just releases the latch but it's not powered like the trunk so you have to manually close it.

**Comment by chrisdrackett** [comment]
This is a good point! I didn't really think too hard about it as I don't really use mine, but the frunk should really just be a release button of some sort that ideally has open/closed status. I wonder what happens if you remove the CLOSE feature on a cover if it would work as expected.

**Comment by purcell-lab** [comment]
> 

Powered drunk is rumoured to be coming
https://www.notateslaapp.com/news/947/is-tesla-adding-a-powered-frunk-to-their-vehicles-app-update-suggests-they-might

For myself neither my frunk not trunk are powered so there are a range of use cases.

**Comment by chrisdrackett** [comment]
yeah, I wonder if its possible to tell the config of the car via the API

**Comment by shred86** [comment]
Hm, yeah we're going to need a way to determine if a vehicle has a powered frunk and/or trunk. The only thing I'm seeing in the JSON response for vehicle data is for the vehicle config: `"can_actuate_trunks": True`. I'd be curious if one of you that has a non-powered trunk could check that attribute to see what it returns.

**Comment by alandtse** [comment]
> Hm, yeah we're going to need a way to determine if a vehicle has a powered frunk and/or trunk. The only thing I'm seeing in the JSON response for vehicle data is for the vehicle config: `"can_actuate_trunks": True`. I'd be curious if one of you that has a non-powered trunk could check that attribute to see what it returns.

It's true for all 3 of my vehicles, two which do not have a powered trunk. My guess is it's just whether the trunk can be controlled at all. It might be part of `option_codes`.

**Comment by shred86** [comment]
I wanted to use option codes for a couple of things but it looks like [they're no longer valid](https://tesla-api.timdorr.com/vehicle/optioncodes) as of August 2019. Looking at the option codes my Model S returns, it still appears to be true.

**Comment by shred86** [comment]
What about these options under `vehicle_config`:

````
            "plg": True,
            "pws": False,
````

Perhaps "plg" is power lift gate? I'm not sure what "pws" is though.

**Comment by alandtse** [comment]
For me plg and pws are true for my model y which is powered. My model3s without are all false.

I think it's plg. PWS is probably pedestrian warning system (i.e., the speakers sounds when driving slow). https://www.tesla.com/ownersmanual/model3/en_cn/GUID-5D8F5B42-90F9-4ED7-9B36-A54BFED1030C.html
