### ISSUE TITLE
Incorrect solar data from API

### ISSUE THREAD

**Issue by llamafilm** [zabuldon/teslajsonpy#350]
In Home Assistant, I noticed weird spikes in the middle of the night where it thinks my Tesla solar panels are suddenly producing power and grid consumption goes negative.  This can't be possible, since the sun is completely dark.  I believe the error is on Tesla's side, but I wanted to post here to see if anyone else has encountered this issue, and to discuss possible workarounds.

What do you think about an option to ignore any data where `load_power` is zero?

I saw a similar issue [here](https://github.com/alandtse/tesla/issues/248) caused by Unknown `grid_status`, but this is different because my `grid_status` is always Active.

Here's a snippet I extracted from the log showing a good response followed by a bad one.

```json
{
  "solar_power": 0,
  "load_power": 136,
  "grid_status": "Active",
  "grid_services_active": false,
  "grid_power": 136,
  "grid_services_power": 0,
  "timestamp": "2022-09-28T02:42:54-07:00",
  "wall_connectors": null
},
{
  "solar_power": 337,
  "load_power": 0,
  "grid_status": "Active",
  "grid_services_active": false,
  "grid_power": -337,
  "grid_services_power": 0,
  "timestamp": "2022-09-28T02:43:04-07:00",
  "wall_connectors": null
}
```

Here's a graph of the full day and also a zoomed in view of the 3hr problematic section.
<img width="1300" alt="24 hours" src="https://user-images.githubusercontent.com/3991046/192957965-c5b42c50-54c8-4a8c-b2ae-3b835ceeb19a.png">
<img width="1297" alt="3 hours" src="https://user-images.githubusercontent.com/3991046/192968001-61da0f81-033b-46be-a3f2-f7c3ab048e79.png">

The iOS Tesla app shows a slightly different problem at the same time.  The CSV data exported from there shows that at 2:45 the load drops to 0 (wrong), but solar production remains steady at 0 (correct).
[Tesla 9-28.csv](https://github.com/zabuldon/teslajsonpy/files/9672264/Tesla.9-28.csv)

**Comment by llamafilm** [comment]
I spoke with Tesla support about this, and they informed me that the Powerblaster clamps in my breaker panel are provided as a "bonus feature" and are not actually supported.  Apparently some Tesla solar customers don't even have this, so I should consider myself "lucky" to have consumption monitoring at all.  They also said that the Powerblasters have been unreliable so they've been phased out.  It sounds like I'll have to buy a different clamp meter.

The two reps I spoke with were completely unaware of the API and could not offer any help about the `solar_power` errors there.

Here's my first attempt at a workaround:
https://github.com/llamafilm/teslajsonpy/commit/5f22fd5b9bcd3bc3979a1704e016024338da4381

**Comment by shred86** [comment]
Tesla support is worthless. Do you have a Powerblaster or Neurio? If it's a recent install, it's likely a Neurio energy monitoring device. It's true they are not providing these in many installs now, but I'd call it far from a "bonus feature" as their website and solar panel user manuel (without powerwall) still advertises home and grid usage monitoring. I had to explain this to them to get them to install the Neurio after my solar system was installed.

There is also a known issue with Neurio CT clamps. Apparently there's a large batch of bad clamps which can cause these faulty readings. I posted about it over at TMC which you can read my summary [here](https://teslamotorsclub.com/tmc/threads/tesla-solar-panels-inverter-no-powerwall-with-neurio-and-two-electrical-panels.271452/page-2#post-7025358). Tesla needs to come out and replace the CT clamps. There's some customers that had the Tesla service technician go through 5+ clamps before finding correct ones.

Unfortunately, your readings are probably not correct (beyond just these errors you're seeing at night). My guess is if you used a clamp meter and compared how much watts your system is pushing/pulling from the grid with what your Tesla app is saying, it will likely be off. That's what I did and there's times it's reading way too low, fairly close or way too high. There's really nothing we can do about bad data coming from Tesla's side.

**Comment by llamafilm** [comment]
Mine is about 3 years old, it's a Powerblaster.  When the system was first installed, the data was wildly inaccurate in the Tesla app because they installed the clamps in the wrong place.  (Clamped around the 100A lines feeding a sub panel, so it did not include the central AC and EV charger.)  To rectify this, they added a splitter and 2 more clamps around those circuits and that made it look better.  But looking closer today, the data from my utility (SCE) still doesn't match the Tesla app.  I will talk with Tesla about it.

![IMG_0393](https://user-images.githubusercontent.com/3991046/195220229-8b07b130-9a32-482f-b932-121bb0e88f9f.jpg)

**Comment by llamafilm** [comment]
You're right, Tesla support is worthless.  They have sent technicians to my house 4 times now to try fixing this monitoring.  Each time, the technician blames the previous one for setting it up wrong.  I've documented their setup each time, and none of them have been the same, LOL.  I've given up on this now and bought an IotaWatt instead.
