### ISSUE TITLE
Tag releases in this repo

### ISSUE THREAD

**Issue by OverloadUT** [zabuldon/teslajsonpy#37]
I am trying to determine if I need to flag the home-assistant version bump with a breaking change label due to potential changing entity_ids. Coming to this repo, I was going to compare the changes between versions when I discovered that there are no version tags at all!

We should have version tags added here so that the changes between versions can be seen.

**Comment by alandtse** [comment]
No entity change yet. I would've noted the breaking change in the HA bump.  I'll tag the current version.

**Comment by alandtse** [comment]
@OverloadUT This is done. Please note for HA I had to do one more [revision](https://github.com/home-assistant/home-assistant/pull/21702) to bump the dependency 0.0.25 to fix an indentation bug that broke updates based on polling . That is not a breaking change either.

The entity change will probably happen in 0.0.26
