### ISSUE TITLE
Sharing

### ISSUE THREAD

**Issue by brian-gates** [zabuldon/teslajsonpy#398]
Add support for https://tesla-api.timdorr.com/vehicle/commands/sharing

Related to: https://github.com/alandtse/tesla/issues/541

**Comment by kalavo** [comment]
According to https://tesla-api.timdorr.com/vehicle/commands/sharing it appears navigation_gps_request and replaced with share

endpoints.json needs to be changed from

```
  "SEND_GPS_TO_VEHICLE": {
    "AUTH": true,
    "TYPE": "POST",
    "URI": "api/1/vehicles/{vehicle_id}/command/navigation_gps_request"
  },
```

..to...

```
  "SHARE": {
    "AUTH": true,
    "TYPE": "POST",
    "URI": "api/1/vehicles/{vehicle_id}/command/share"
  },
```

...I'm not a programmer, and never used Github. Trying to figure out how Pull Requests work, but someone might be able to beat me to this and give it the nod?
