### ISSUE TITLE
Add sentry

### ISSUE THREAD

**Issue by riemers** [zabuldon/teslajsonpy#43]
As from the tweets from [Elon ](https://twitter.com/elonmusk/status/1108965358998712321) you can get the idea that Sentry will have multiple options (always on, home, locations etc) we have no clue how long this will be. If you can add it, it would be as simple as "not driving? put on sentry mode" and we could easilly say "exclude if in this location" if we wanted too.

**Comment by alandtse** [comment]
At least one reference here:
https://tesla-api.timdorr.com/vehicle/commands/sentrymode

**Comment by alandtse** [comment]
So the only thing this would do is to enable or disable it. Is the goal to just have an additional way to disable it outside of the regions the native UI supports?
