### ISSUE TITLE
Change to https://owner-api.teslamotors.com/api/1/vehicles API

### ISSUE THREAD

**Issue by grillp** [zabuldon/teslajsonpy#448]
teslajsonpy Version: 3.9.9

Seems Tesla has changed access to the https://owner-api.teslamotors.com/api/1/vehicles call.. This means that calls to `vehicle_list()` now fails with:

`requests.exceptions.HTTPError: 412 Client Error: Endpoint is only available on fleetapi. Visit https://developer.tesla.com/docs for more info for url: https://owner-api.teslamotors.com/api/1/vehicles`

It appears you have to use `https://owner-api.teslamotors.com/api/1/products` now and parse out all vehicles..

sample app:
```python
import teslapy
token = "<tesla api token>"
with teslapy.Tesla('elon@tesla.com') as tesla:
    if not tesla.authorized:
        tesla.refresh_token(refresh_token=token)
    vehicles = tesla.vehicle_list()
    print(vehicles[0])
```
results:
```
Traceback (most recent call last):
  File "/Users/me/work/personal/teslapy/test_tesla.py", line 6, in <module>
    vehicles = tesla.vehicle_list()
               ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/teslapy/__init__.py", line 375, in vehicle_list
    return [Vehicle(v, self) for v in self.api('VEHICLE_LIST')['response']]
                                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/teslapy/__init__.py", line 369, in api
    return self.request(endpoint['TYPE'], uri, serialize,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/teslapy/__init__.py", line 158, in request
    response.raise_for_status()  # Raise HTTPError, if one occurred
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 412 Client Error: Endpoint is only available on fleetapi. Visit https://developer.tesla.com/docs for more info for url: https://owner-api.teslamotors.com/api/1/vehicles
```

**Comment by jaymunro** [comment]
An email from TeslaFi 2 days ago at 3:54am, Jan 23 UTC:

> Hello,
> 
> Sorry for interruption!
> 
> In the past few hours, Tesla has changed to a new officially supported Tesla API to connect your car to the TeslaFi.com service.
> 
> Please login to your TeslaFi.com account as soon as possible, if you have not already changed your connection, to reconnect TeslaFi.com with your car so logging will resume as soon as possible.
> 
> When you login, you will see a message in the top right of the site with instructions on how to make the change.  Please reference the image below as an example.  This process will only take a few moments. Feel free to go to help->open and open a support ticket if you happen to run into any issues.
> 
> While we know this is an inconvenience, it’s a wonderful change that Tesla is officially supporting 3rd party companies like TeslaFi.com and it will provide a stable foundation for us in the future!
> 
> Thank you for your time and membership,
> The TeslaFi.com Team

I made the change at TeslaFi which required re-authentication, a choice between A. legacy web access (soon to be deprecated) or B. direct access to the car. I chose B. and tapped a link to open the Tesla app on my phone where I needed to approve TeslaFi directly accessing the car.

My take on this is that finally the Tesla API is official and supported. YAY!
Then teslajsonpy could have minor modifications to work with A, however B. Would be needed in the long term.

**Comment by jaymunro** [comment]
How about changing the title of this to:?
Change endpoints to support official Tesla API released Jan 23, 2024

So that it gets the attention it deserves.

**Comment by alandtse** [comment]
As noted in https://github.com/alandtse/tesla/issues/774 and https://github.com/alandtse/tesla/issues/743 Tesla has removed the old API and requires a third-party integrator to integrate with their API. This requires payment to Tesla. While the url change may work; someone will need to test it and make sure it works and submit a PR. It may not actually do anything given the API deprecation.
