### ISSUE TITLE
Enable GitHub actions

### ISSUE THREAD

**Issue by alandtse** [zabuldon/teslajsonpy#45]
I can also assist in adding some CI if you enable [GitHub Actions](https://github.com/features/actions). However, I'll need access to add secrets so I can add a personal access token to push to this repo and to add my credentials to push to pypi automatically.

**Comment by zabuldon** [comment]
@alandtse Thanks. done.

**Comment by alandtse** [comment]
@zabuldon Thanks I saw the option is now up. However, for the Action to be able to push to itself, it'll need a personal access code setup. 

That means either you'll have to create one and let me know the secret name or you can give me admin rights so I create secrets.  The only requirement is `public_repo`.

**Comment by zabuldon** [comment]
@alandtse which one should I enable. Don't see an option to make you admin too.

**Comment by alandtse** [comment]
Oh, maybe you can't for personal repo?

You can just create one a personal access token for the Actions to use.
Under [personal access tokens](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line) -> repo -> `public_repo`. That is the only permission needed to push back to a repo.

Then save it under a [secret](https://help.github.com/en/github/automating-your-workflow-with-github-actions/virtual-environments-for-github-actions#creating-and-using-secrets-encrypted-variables) named `GH_TOKEN`. I'll be accessing it the same way as for this [repo](https://github.com/custom-components/alexa_media_player/blob/master/.github/workflows/semantic_release.yml#L30).

You'll also want to create similar secrets for your pypi auth. That way the action can also publish.

**Comment by zabuldon** [comment]
@alandtse It is not personal repo. I already made it public.

**Comment by alandtse** [comment]
Sorry I mean non-organization repos. I don't think you can have more than one person able to create secrets yet.

**Comment by zabuldon** [comment]
@alandtse I've created secret. Please check.

**Comment by alandtse** [comment]
Thanks. About to sleep, but I'll test building an Action in the next few days. Do you also want to create secrets for pypi user and pass so it can also publish it automatically? The tool is [semantic-release](https://python-semantic-release.readthedocs.io/en/latest/envvars.html#pypi-password). Just let me know the variables names and I'll put them in the workflow.

**Comment by zabuldon** [comment]
@alandtse Let's discuss it online. If you have discord please contact me Zabuldon#5255

**Comment by alandtse** [comment]
I don't think semantic-release supports pypi tokens yet. I've put up an action you can [check out](https://github.com/zabuldon/teslajsonpy/commit/ad276b503de55daa9926cca633aac18131bd8fae/checks?check_suite_id=285566116) . Check out the semantic release step which is currently set for dry-run only.

I may not be online tonight, but my discord is alandtse#5464.

**Comment by alandtse** [comment]
Ok, I figured out how to use tokens. I think it's sourcing it correctly now.
https://github.com/zabuldon/teslajsonpy/commit/4d2abb4a166002cad7ef1ca4efccf6bf6d08471f/checks?check_suite_id=285710280.
