### ISSUE TITLE
Support for Tesla HTTP Proxy

### ISSUE THREAD

**Issue by llamafilm** [zabuldon/teslajsonpy#452]
Since Tesla has deprecated the Owner API, I believe the easiest path to keep using this library (and the Home Assistant integration that depends on it) is to use Tesla's [HTTP Proxy](https://github.com/teslamotors/vehicle-command).  I've built a Home Assistant add-on that does exactly this, plus it handles the initial authorization flow which is somewhat complicated.  Since it's completely self-hosted, it does not require trusting any third party with your credentials.  And we can still benefit from the new public key security model.

I haven't yet had time to test with this library, but I believe it only requires 3 changes:
- optional custom `API_URL`
- optional custom SSL certificate (because the HTTP proxy is not publicly accessible)
- optional custom refresh token

Add-on is here: https://github.com/llamafilm/tesla-http-proxy-addon

**Comment by purcell-lab** [comment]
Great work!

**Comment by alandtse** [comment]
We'll welcome the PR when it's provided.

**Comment by alandtse** [comment]
closed by #454
