### ISSUE TITLE
Authentication method causes logouts in apps

### ISSUE THREAD

**Issue by wernerb** [zabuldon/teslajsonpy#47]
I'm using the library using home-assistant integration and works fine. However, after using this integration I notice i'm being forcefully logged out of my android app every once in a while which is annoying when I want to unlock the car :) 

This makes me believe the repeated authentications is rate-limited in some way, or at least, there are protections in place.

Instead of re-authenticating with the user/pass every time, we should use the refresh_token instead to fix this behaviour. 

https://tesla-api.timdorr.com/api-basics/authentication#post-oauth-token-grant_type-refresh_token

**Comment by alandtse** [comment]
Not sure it's the cause of the relogins (I've always thought Tesla forces a relogin every month or so), but I have a oauth version in the works which will happen at the same time as async. Need to clean it up and submit the PR here and in HA.
