### ISSUE TITLE
Add extensive HVAC control

### ISSUE THREAD

**Issue by MarvinSchenkel** [zabuldon/teslajsonpy#62]
It would be great if we would be able to fully control HVAC mode, e.g. turn the HVAC to HIGH which would allow me to quickly defrost my Model 3. At the moment, we are only able to turn it on or off.

**Comment by alandtse** [comment]
I'm not sure the Tesla API allows direct control of the fan. Can't you set the temperature to a high temperature and start the HVAC for the same effect?

**Comment by tobbensoft** [comment]
@alandtse 

https://tesla-api.timdorr.com/vehicle/commands/climate#post-api-1-vehicles-id-command-set_preconditioning_max

**Comment by alandtse** [comment]
Is there an HA climate entity or mode that matches this well? Otherwise we could add a switch.

**Comment by tobbensoft** [comment]
I can't find any suitable entity in the documentation.

Are we free to use any word there?  Thinking about if ```max``` or ```defrost``` is best to use.

**Comment by alandtse** [comment]
I guess based off what it does, `defrost` is best.

**Comment by alandtse** [comment]
Please test the PR. You will need to update your Tesla in HA to test it. You can do that by copying to the custom_component directory.
