### ISSUE TITLE
Support opening / closing the charge port automatically on returning home

### ISSUE THREAD

**Issue by cby016** [zabuldon/teslajsonpy#63]
I think it would be pretty sweet for the charge port to open automatically when I pull into the garage.

**Comment by alandtse** [comment]
You mean after you've parked? This can already be enabled but you need something to leverage this library. If you're referring to HA, it's probably already possible using automations. It's not something that would be built in this library.

**Comment by cby016** [comment]
Yes I would set up the automation in HA. So you are telling this library already exposes the ability to open / close the charge port to HA? Maybe the [HA Tesla Docs](https://www.home-assistant.io/integrations/tesla/) need to be updated because right now they don't mention the ability to open the charge port.

**Comment by alandtse** [comment]
Yes, docs probably needs to be updated. Look for `lock.XXXX_charger_door_lock`.
