### ISSUE TITLE
Switch to two branch system

### ISSUE THREAD

**Issue by alandtse** [zabuldon/teslajsonpy#72]
@zabuldon now that we have more people helping, I was thinking it made sense to set up a two branch system where there's a `dev` branch for PRs to commit to and `master` is used for releases only.

Any objections? I don't have the rights to change the default branch to `dev` though.

**Comment by zabuldon** [comment]
It's okay for me

**Comment by alandtse** [comment]
Can you set the dev branch to default? Or if you can give me admin rights to the repo I think I could do it too.

**Comment by zabuldon** [comment]
Done. Changed default branch to dev. Going to check how to grant admin
tomorrow.
