### ISSUE TITLE
Add sensor for detecting charging cable is attached

### ISSUE THREAD

**Issue by Finnsen** [zabuldon/teslajsonpy#9]
It would be nice to be able to read if a charging cable is attached, so that one can automate reminders for i.e. attaching the cable.

In the Charge State query, the following two responses would be great to see:
"conn_charge_cable": "IEC" [IEC, SAE]
"charge_port_latch": "Engaged"

Edit:
After investigating the "charge state" response, adding a sensor called something like "ChargeCableAttatchedSensor" which basically is true when "charge_state" parameter is not "Disconnected"

**Comment by alandtse** [comment]
I actually don't think charge_state parameter is enough. I think you may have been correct with the `conn_charge_cable` or the `charge_port_latch` options. I'll test it out and see if there's a good algorithm

**Comment by alandtse** [comment]
I looked a bit closer and `charge_state` is probably enough. The thing is we already have a ChargerConnectionSensor. Looking at the code, I think it might be a bug in the way it's returning the connection info. It's a connectivity sensor in HA so I think that's it's intent although the logic could indicate it's for detecting charging?

@zabuldon what did you intend the charger connection binary sensor to represent?  Was that intended to show a connected cable? If so, I think checking for `Disconnected` is the only requirement. If you intended for power, it's probably redundant to the Charging switch.  Would you be opposed with changing the logic so it's actually a connection sensor?
